/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void btnResetClick(GButton source, GEvent event) { //_CODE_:btnReset:933479:
  println("btnReset - GButton >> GEvent." + event + " @ " + millis());
  resetAngle();
} //_CODE_:btnReset:933479:

public void btnSpinClick(GButton source, GEvent event) { //_CODE_:btnSpin:521123:
  println("btnSpin - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:btnSpin:521123:

public void txtAreachange1(GTextArea source, GEvent event) { //_CODE_:txtArea:859644:
  println("txtArea - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:txtArea:859644:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  btnReset = new GButton(this, 43, 52, 210, 42);
  btnReset.setText("Reset");
  btnReset.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  btnReset.addEventHandler(this, "btnResetClick");
  btnSpin = new GButton(this, 42, 201, 211, 103);
  btnSpin.setText("Spin!");
  btnSpin.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  btnSpin.addEventHandler(this, "btnSpinClick");
  txtArea = new GTextArea(this, 68, 108, 160, 80, G4P.SCROLLBARS_NONE);
  txtArea.setOpaque(true);
  txtArea.addEventHandler(this, "txtAreachange1");
}

// Variable declarations 
// autogenerated do not edit
GButton btnReset; 
GButton btnSpin; 
GTextArea txtArea; 

